### ISSUE TITLE
Deck editing too buggy

### ISSUE THREAD

**Issue by RyuYol** [LagomInteractive/cosmic-game#11]
People cannot make decks on the deck editor for the site. It keeps going to "0/20 olle" and no way to fix... (not refreshing, starting a new deck nor giving developer fixes it). I can fix this issue on my end but others trying to build decks can't :/

**Comment by Yogsther** [comment]
Could this be because they do not have any cards in their inventory?

**Comment by Yogsther** [comment]
Just checked with a new account, it should be empty for someone with no cards in their inventory, but it should correctly state their username, not "olle". So they have indeed bugged out. I cannot reproduce the issue, could be an outdated browser (Safari?)

**Comment by RyuYol** [comment]
Yes, i have given the account in question cards and it did not function. The person was using the same browser as me (OperaGX).

**Comment by Yogsther** [comment]
Part of this bug was not being able to view decks when not logged out, that is fixed.
