### ISSUE TITLE
Setting Unit field size limit to 7-8

### ISSUE THREAD

**Issue by RyuYol** [LagomInteractive/cosmic-game#13]
So as we talked about on Friday, both sides need a limit to how many units can be on field at once. I believe we decided on it being around 7-8 units.

**Comment by Yogsther** [comment]
I this not working? It should be working.

**Comment by RyuYol** [comment]
Oh, i may not have tested it. I saw it on my notes and thought it wasn't implemented yet. I will test it now to confirm.

**Comment by Yogsther** [comment]
It almost works. If a unit has a battlecry that spawns units, it checks for room of every unit that spawns, but ignores the original unit, that is placed into the game last. The original unit can be placed into the game before running its battery event, this should fix the problem.
