### ISSUE TITLE
Allowing us to set Card Rarity on the site

### ISSUE THREAD

**Issue by RyuYol** [LagomInteractive/cosmic-game#14]
We do not require it to function mechanically with rarity rates when unpacking, currently we just need a way to define "rare cards" so that they show up in a match with different crystals. The only thing that we may want added is that the highest rarity cards: Legendary & Developer. Stay on only 1 copy per deck.

**Comment by Yogsther** [comment]
Rarity added to the website editor (not yet visual on cards or ingame)
