### ISSUE TITLE
Taunt Mechanic Revamp

### ISSUE THREAD

**Issue by RyuYol** [LagomInteractive/cosmic-game#18]
A big thing that we were discussing on was to do with out taunt mechanic. We decided to spice it up by making it only protect it's adjacent allies and the player, rather than every ally. This makes our mechanic differ from how others have it. At the same time, it would be appropriate to rename it to that and make VFXs that connect itself to its protected allies.

**Comment by Yogsther** [comment]
Not enought time to add , also we locked new game features last week.
